### ISSUE TITLE
Failed to execute webm.exe

### ISSUE THREAD

**Issue by Sandy2193** [Ogrlemonsoup/Webm#1]
I got this problem when i was trying to execute the webm.exe using windows
failed to execute script ''Webm'' due to unhandled exception: FileNotFoundError: [Errno 2] No such file or directory:C:\Users\AppData\Local\Temp\_MEI\config.json

**Comment by Ogrlemonsoup** [comment]
This is a well known issue because I always forget to switch one setting before compiling. Should work now.
